# fly.toml app configuration file generated for pandaku on 2024-04-20T14:55:25+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pandaku'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3030
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
